services:
  nodejs:
  # docker exec -it docker_nodejs_chat-app-1 /bin/bash
    build: .
    ports:
      - '80:80'
    env_file:
      - .env # Đọc biến môi trường từ file .env
    depends_on:
      - mongodb
      - redis
    volumes:
      - .:/app

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ca9f717cc89a11a2af2eaa1b883a90ce
    volumes:
      - redis:/data
volumes:
  mongo-data:
  redis:
    driver: local
